CREATE DATABASE IF NOT EXISTS functional;

USE functional;

DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(ID INTEGER NOT NULL AUTO_INCREMENT,
NOM VARCHAR(25) NOT NULL,
PRENOM VARCHAR(25) NOT NULL,
PRIMARY KEY (ID));

ALTER TABLE functional.USER AUTO_INCREMENT = 100;
